Timesheet_Management_Project/timesheetManagement/timesheetManagement/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('userManagement.urls')),
    path('workdays/', include('workdayManagement.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Timesheet_Management_Project/timesheetManagement/userManagement/urls.py
from django.urls import path
from userManagement import views

app_name='userManagement'
# #URLPatterns for function based views
urlpatterns = [
    path('', views.home_view, name='home'),
    path('list/', views.UserList.as_view(), name='user_list'),
    #path('<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('new/', views.user_new, name='user_new'),
    #path('new/',views.UserCreate.as_view(),name='user_new'),
    #path('<int:user_id>/update', views.user_update, name='user_update'),
    path('<int:pk>/update', views.UserUpdate.as_view(), name='user_update'),
]

Timesheet_Management_Project/timesheetManagement/workdayManagement/urls.py
from django.urls import path
from workdayManagement import views

app_name = 'workdayManagement'
# #URLPatterns for function based views
urlpatterns = [
    path('', views.WorkList.as_view(), name='work_list'),
    path('new/', views.WorkCreate.as_view(), name='work_new'),
    path('<int:pk>/update', views.WorkUpdate.as_view(), name='work_update'),
    # path('<int:work_id>/update', views.work_update, name='work_update'),
]

Timesheet_Management_Project/timesheetManagement/workdayManagement/models.py
from django.db import models
from datetime import date

# Create your models here.

from userManagement.models import User


class Location(models.Model):
    location=models.CharField(max_length=50)
    sector=models.CharField(max_length=50)

    def __str__(self):
        return self.location


class Workday(models.Model):
    work_date=models.DateField(default=date.today)
    location=models.ForeignKey(Location,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    time_in=models.TimeField()
    time_out=models.TimeField()
    hours_code=models.CharField(max_length=5)

    def clean(self, *args, **kwargs):
        from django.core.exceptions import ValidationError
        if self.time_out < self.time_in:
            raise ValidationError("Time_out cannot be less than Time_in")
        super().clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

Timesheet_Management_Project/timesheetManagement/workdayManagement/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError

from workdayManagement.models import Workday


class WorkForm(forms.ModelForm):

    work_date = forms.DateField(initial=datetime.date.today)
    location = forms.CharField(max_length=30, required=True)
    user = forms.CharField(max_length=30, required=True)
    time_in = forms.TimeField()
    time_out = forms.TimeField()
    hours_code = forms.CharField(max_length=5)

    class Meta:
        model = Workday
        fields = ('work_date', 'location', 'user', 'time_in', 'time_out', 'hours_code')

Timesheet_Management_Project/timesheetManagement/workdayManagement/views.py
from django.contrib.auth.models import User
from django.db.models import Model
from django.forms import ModelForm
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from django.urls import reverse, reverse_lazy

# Create your views here.
from django.views.generic import ListView, CreateView, UpdateView

from workdayManagement.models import Workday

from workdayManagement.forms import WorkForm




class WorkList(ListView):
    #model = Workday
    context_object_name = 'Work'
    template_name = 'workdayManagement/work_list.html'
    queryset = Workday.objects.select_related('user')

class WorkCreate(CreateView):
    model = Workday
    #form_class = WorkForm
    fields = ('work_date', 'location', 'user', 'time_in', 'time_out', 'hours_code')
    template_name = 'workdayManagement/work_new.html'
    success_url = reverse_lazy('workdayManagement:work_list')



class WorkUpdate(UpdateView):
    model = Workday
    fields = ('work_date', 'location', 'user', 'time_in', 'time_out', 'hours_code')
    template_name = 'workdayManagement/work_update.html'
    success_url = reverse_lazy('workdayManagement:work_list')


def Work_Update(request, work_id):

    #work = get_object_or_404(Workday, pk=work_id)
    work = Workday.objects.get(pk=work_id)
    form = WorkForm(request.POST or None,instance=work)

    if request.method == "POST":
        if form.is_valid():
            work = form.save()
            work.save()
            return HttpResponseRedirect(reverse('workdayManagement:work_list'))
    else:
        return render(request, 'workdayManagement/work_update.html', {'form': form})

Timesheet_Management_Project/timesheetManagement/templates/workdayManagement/work_list.html
{% extends '../base_timesheet.html' %}

{% block title %}Workday List{% endblock title %}

{% block content %}
    {% if user %}<a href="{% url 'workdayManagement:work_new' %}">Add Workday</a>{% endif %}
    {% if object_list %}

        <table border="1">
            <tr bgcolor="yellow"><td>Doctor</td><td >Work Date</td><td >Location</td><td >Time In</td>
            <td >Time Out</td><td>Hours Code</td></tr>
        {% for work in object_list %}

            <tr><td><a href="{% url 'workdayManagement:work_update' work.id %}">{{work.user}}</a></td><td>{{work.work_date}}</td><td>{{work.location}}</td><td>{{work.time_in}}</td>
            <td>{{work.time_out}}</td><td>{{work.hours_code}}</td>
        {% endfor %}
        </table>
    {% else %}
        <p>No workdays available.</p>
    {% endif %}
{% endblock content %}

Timesheet_Management_Project/timesheetManagement/templates/workdayManagement/work_new.html
{% extends '../base_timesheet.html' %}
{% block title %}Add User{% endblock title %}

{% block content %}
   <form method="post" action="" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        <table> 
           {{ form.as_p }}

        </table>
        <button type="submit" value="Save">Save</button>
        <a href="{% url 'workdayManagement:work_list' %}" > Cancel </a>
    </form>
{% endblock content %}

Timesheet_Management_Project/timesheetManagement/templates/workdayManagement/work_update.html
{% extends '../base_timesheet.html' %}
{% block title %}Update Workday {% endblock title %}

{% block content %}
    <form method="post" >{% csrf_token %}
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Save</button>
        <a href="{% url 'workdayManagement:work_list' %}" > Cancel </a>
    </form>
{% endblock content %}