Timesheet_Management_Project/timesheetManagement/timesheetManagement/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('userManagement.urls')),
    path('workdays/', include('workdayManagement.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Timesheet_Management_Project/timesheetManagement/userManagement/urls.py
from django.urls import path
from userManagement import views

app_name='userManagement'
# #URLPatterns for function based views
urlpatterns = [
    path('', views.home_view, name='home'),
    path('list/', views.UserList.as_view(), name='user_list'),
    #path('<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('new/', views.user_new, name='user_new'),
    #path('new/',views.UserCreate.as_view(),name='user_new'),
    #path('<int:user_id>/update', views.user_update, name='user_update'),
    path('<int:pk>/update', views.UserUpdate.as_view(), name='user_update'),
]

Timesheet_Management_Project/timesheetManagement/workdayManagement/urls.py
from django.urls import path
from workdayManagement import views

app_name = 'workdayManagement'
# #URLPatterns for function based views
urlpatterns = [
    path('', views.WorkList.as_view(), name='work_list'),
    path('new/', views.WorkCreate.as_view(), name='work_new'),
    path('<int:pk>/update', views.WorkUpdate.as_view(), name='work_update'),
    # path('<int:work_id>/update', views.work_update, name='work_update'),
]

Timesheet_Management_Project/timesheetManagement/userManagement/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    image = models.ImageField(upload_to='userManagement/', null=True, blank=True)

Timesheet_Management_Project/timesheetManagement/userManagement/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from userManagement.models import Doctor


class UserForm(forms.Form):
    firstname = forms.CharField(max_length=30, required=False)
    lastname = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254)
    password = forms.CharField(max_length=30, required=False)
    description = forms.CharField(max_length=30, required=False)
    image = forms.ImageField(required=False)


    class Meta:
        model = Doctor
        fields = ('firstname', 'lastname', 'email', 'password1', 'password2', 'description', 'image')


class AuthUserCreateForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254)
#     password = forms.CharField(max_length=30, required=False) # We don't need this since UserCreationForm has password1 and password2 already .. but does not have first name, last name and email.. so those fields makes sense .
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2','username','is_superuser','is_staff','is_active')


class DoctorCreateForm(forms.ModelForm):
    description = forms.CharField(max_length=30, required=False)
    image = forms.ImageField(required=False)

    class Meta:
        model = Doctor
        exclude = ('user',)
        

Timesheet_Management_Project/timesheetManagement/userManagement/views.py
from itertools import chain
from operator import attrgetter

from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User

from django.urls import reverse, reverse_lazy
from userManagement.models import Doctor
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from userManagement.forms import UserForm

# Create your views here.
from userManagement.forms import AuthUserCreateForm, DoctorCreateForm


class UserList(ListView):

    context_object_name = 'Users' # use all lower case, that's industry norms for naming contextobjectname
    template_name = 'userManagement/user_list.html'

    def get_queryset(self):
        queryset = Doctor.objects.select_related('user')
        return queryset

    

class UserDetail(DetailView):
    model = Doctor
    context_object_name = 'Users'
    template_name = 'userManagement/user_detail.html'


def user_new(request):
    if request.method == "POST":
        # form = UserForm(request.POST)
        authuserform = AuthUserCreateForm(request.POST)
        doctorform = DoctorCreateForm(request.POST)
        print(authuserform, doctorform)

        if authuserform.is_valid() and doctorform.is_valid():

            user = authuserform.save()            
            doctor = doctorform.save(commit=False)
            doctor.user = user
            doctorform.save()
            return HttpResponseRedirect(reverse('userManagement:user_list'))
        else:
            print(authuserform.is_valid(),doctorform.is_valid())
            return render(request, 'userManagement/user_new.html', {'authuserform': authuserform, 'doctorform': doctorform})
    else:
        authuserform = AuthUserCreateForm()
        doctorform = DoctorCreateForm()
        return render(request, 'userManagement/user_new.html', {'authuserform': authuserform, 'doctorform': doctorform}) # template will receive these 2 forms 


class UserCreate(CreateView):
    form_class = UserForm
    template_name = 'userManagement/user_new.html'
    success_url = reverse_lazy('userManagement:user_list')


def user_update(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    form = UserForm(request.POST or None, instance=user)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            user.save()
            return HttpResponseRedirect(reverse('userManagement:user_list'))
    else:
        return render(request, 'userManagement/user_update.html', {'form': form})


class UserUpdate(UpdateView):
    form_class = UserForm
    template_name = 'userManagement/user_update.html'
    success_url = reverse_lazy('userManagement:user_list')

def home_view(request):
    return render(request, 'userManagement/welcomepage.html')

Timesheet_Management_Project/timesheetManagement/templates/userManagement/user_list.html
{% extends '../base_timesheet.html' %}

{% block title %}Users List{% endblock title %}

{% block content %}

    {% if object_list %}

        {% for user in object_list %}


            <tr><td><img src="{{user.image.url}}" width="100"></td><td> {{user.description}}</td></tr><br><br

        {% endfor %}

    {% else %}
        <p>No Users are available.</p>
    {% endif %}
{% endblock content %}

Timesheet_Management_Project/timesheetManagement/templates/userManagement/user_new.html
{% extends '../base_timesheet.html' %}
{% block title %}Add User{% endblock title %}

{% block content %}
   <form method="post" action="" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        <table> 
           {{ authuserform.as_p }}
           {{ doctorform.as_p }}
        </table>
        <button type="submit" value="Save">Save</button>
        <a href="{% url 'userManagement:user_list' %}" > Cancel </a>
    </form>
{% endblock content %}




<!---<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <form method="post" action="{% url 'userManagement:user_new' %}">

        {% csrf_token %}
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="Save">Save</button>
        <a href="{% url 'userManagement:user_list' %}" > Cancel </a>
    </form>
</body>
</html>--->

Timesheet_Management_Project/timesheetManagement/templates/userManagement/welcomepage.html
{% extends '../base_timesheet.html' %}

{% block title %}Time Sheet Managementt{% endblock title %}

{% block content %}
    <a href="{% url 'userManagement:user_list' %}">Doctors</a><br>
    <a href="{% url 'userManagement:user_new' %}">Add Doctor</a><br><br>

    <a href="{% url 'workdayManagement:work_list' %}">Work Data </a><br>
    <a href="{% url 'workdayManagement:work_new' %}">Add Work Day </a><br><br>




{% endblock content %}